### ISSUE TITLE
Azure acces

### ISSUE THREAD

**Issue by ffrriiccii** [cloudsteak/mentor-klub-cloud#1]
Kedves Tiibor!

Frici vagyok a  múlt héten indult 6 hetes csütörtöki Azure képzésről.
Tegnap (vasárnap) este igényeltem "tanári" hozzáférést az Azure-hoz.
beírtam az egyetlen egy kódot amit találtam, igaz az a képzéshez történő csatlakozáshoz és a visszanézéshez kell.
Sajnos semmilyen válasz levelet nem kaptam.

Üdvözlettel:
Németh László (Frici)

**Comment by ffrriiccii** [comment]
Hahó, látja ezt valaki egyáltalán? :-(

**Comment by the1bit** [comment]
Szia,

Ne haragudj. :-)

Remélem azóta megoldódott. 

Ha nem, akkor írj kérlek. :-)
