### ISSUE TITLE
[Q]: Hogyan lehet egy fork-olt github oldalon levő új Branch-et belefordítani a saját fork-olt main-omba? Na ez most szép magyar lett :D

### ISSUE THREAD

**Issue by Gomboc7** [cloudsteak/mentor-klub-cloud#10]
### Miben segíthetek?

Azért írok mert sikerült lefolk-olni a https://github.com/cloudsteak/trn-node-demo oldalt, a https://github.com/Gomboc7/trn-node-demo -ra, saját repository-t csinálni.
Ezt sikerült is telepítenem Azure-ba.
Viszont amikor módosítani akartam egy saját Branch-en, akkor azt nem tudom befuttatni a main-omba, hanem folyton az eredeti cloudsteak-os main-ba akarja csak pull-olni. Itt van is pár request-em, ahol látható, hogy próbálom, de nyilván nem oda akarom... de nem találom hogy kell a sajátomba...

### Témakör

Azure

**Comment by the1bit** [comment]
Itt van a szál egy másik repo-ban!
https://github.com/cloudsteak/trn-node-demo/issues/102
