### ISSUE TITLE
[I]: Korábbi regisztrációnál használt hitelkártya elutasítva

### ISSUE THREAD

**Issue by BeniBenB** [cloudsteak/mentor-klub-cloud#11]
### Mi történt?

Tegnap töröltem az azure fiókom, most létrehoztam egy másikat új email címmel, de ha azon belül az ingyenes használatra kattintok, akkor nem fogadja el a hitelkártyám, ami a korábbi fiókomhoz volt beállítva, az ingyenes használat érdekében.
Mit tehetek most, hogy tudjam a korábbi hitelkártyám használni a hitelesítéshez?
![Clipboard_11-15-2024_01](https://github.com/user-attachments/assets/72a964be-7eda-40cc-8f02-ff6730138784)

Előre is köszönöm a segítséget!

### Témakör

Azure

**Comment by the1bit** [comment]
Szia,

Azure nem engedi, hogy egy bankkártyát többször használj fel "ingyenes" regisztrációhoz.

Az alábbi adatokat figyelik:
- Bankkártya
- Email
- Címed

Használj másik kártyát. 😊

**Comment by BeniBenB** [comment]
Szia,

Na, így sikerült. Kérhetek egy meghívót a tanfolyam címtárához?

Előre is köszönöm.

Bence

**Comment by the1bit** [comment]
Szia,

Örülök, hogy sikerült. :-)

Ha jogosultságra van szükséged, akkor tudsz igényelni a több hetes képzés oldalán. :-)

Üdv:
Tibi

**Comment by BeniBenB** [comment]
Szia,

Igényeltem, ahogy javasoltad, de az alábbi üzenetet kaptam:
Hozzáférési kérésed az Azure több hetes képzés előfizetéséhez elutasításra került.

"Sajnálom. Talán rossz email címet adtál meg vagy már szerepelsz az előfizetés felhasználói között."

Ezt követően próbáltam másik email címet is de nem jött semmilyen email arra.

Üdv.: Bence

**Comment by the1bit** [comment]
Azért, mert már van azzal az email címmel jogod.
