### ISSUE TITLE
[Q]: Azure account csatlakozas

### ISSUE THREAD

**Issue by Gomboc7** [cloudsteak/mentor-klub-cloud#12]
### Miben segíthetek?

Szia Tibor,

Nekem volt már egy Azure accountom, és most kértem a felvételemet a mentorklub Azure accountba. 
Megkaptam a meghívót, elfogadtam, és erre a portálon a saját accountomba lép be (lgombos2 kukac gmail)
Itt hol látom a Mentorklub resource-ket? csak a sajátjaimat látom.

![image](https://github.com/user-attachments/assets/4ebaafd9-cc02-40b4-9eba-0b7cfde1b0c3)

Köszi,
Laci

### Témakör

Azure

**Comment by the1bit** [comment]
Szia,

Kérlek olvasd el az értesítő levelet és nézd meg a videót is.

Mindig győződj meg, hogy a megfelelő címtárat választod, mielőtt hibajegyet nyitsz.

Köszönöm. 🙂

**Comment by Gomboc7** [comment]
Ok, sikerült a Cloudsteak címtár választása, köszi a gyors segítséget
![image](https://github.com/user-attachments/assets/6193d2be-ddbf-4004-a26a-6e5dab28ca92)

**Comment by Gomboc7** [comment]
Viszont a Devops-ban nem látom a Mentorklub projektet, csak újat tudok létrehozni a Cloudsteak-on belül:
![image](https://github.com/user-attachments/assets/c87857be-4528-488d-8c32-4846d4b97af8)

Ez miért van?
Köszi!
Laci
