### ISSUE TITLE
[I]: AzureDevops

### ISSUE THREAD

**Issue by Gomboc7** [cloudsteak/mentor-klub-cloud#13]
### Mi történt?

Sikerült a Directory váltás Cloudsteak-ra, köszönöm a hintet.
Viszont a Devops-ban nem látom a Mentorklub projektet, csak új organization-t tudok létrehozni a Cloudsteak-on belül:
image

Ez miért van?
Miután itt létrehozok saját projektet, és ott egy Pipeline-t, ahogy a videóban van, én nem látom a Mentorklubos kapcsolatokat, ha a sajátomat használom, akkor meg ilyen hibával áll le:

Details
Other Errors
1 error(s), 0 warning(s)
	The pipeline is not valid. Job Build: Step Docker input containerRegistry references service connection f4f94a44-0505-4235-9347-4926b8fef7a4 which could not be found. The service connection does not exist, has been disabled or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.

Hogyan használhatom a Mentorklubos service connection-t?
Köszi szépen, és bocs ha megint  valami nyilvánvalót kérdezek! :-D

Laci

### Témakör

Azure

**Comment by the1bit** [comment]
Szia,

Új organisation-t biztosan nem tudsz létrehozni a CloudSteak-en belül, mert a CloudSteak maga az organisation.

Saját magadnak létre kell hoznod organisation-t. 

A MentorKlub project a CloudSteak organisation-on belül van.

Mivel a MentorKlub "Service Connection"-ök a MentorKlub projekthez tartoznak, így azokhoz a project-en kívülről nem lehet hozzáférni. (Baj lenne ha ez másképpen lenne)

#Az általad küldött hibaüzenetre pedig már megadtam a választ múlt héten a képzés alatt: "Az Azure DevOps egy u.n. Service Principal segítségével kapcsolódik az Azure előfizetéshez, ahol az ACR van. Egy Service Principal létrehozásához tulajdonosi vagy társ tulajdonosi jogosultságra van szükség. Ez nektek nincs meg, ezért nem fogsz tudni Te kapcsolatot ilyen módon létrehozni az AzureKépzés előfizetéshez."

Biztos vagy benne, hogy jó Organisation-ben vagy?

https://dev.azure.com/cloudsteak/MentorKlub

**Comment by Gomboc7** [comment]
Nem, ezt az én saját Oauth connection-ommal csináltam. Arra emlékeztem, hogy mondtad, hogy új service principal-t nem tudok létrehozni nálatok.  
Most a Mentorklubban is csináltam egyet a saját connection-ommal, de ez meg retainolódik, nem csinál semmit, megnézheted..

Viszont akkor mi a megoldás? Saját organization, saját project, saját Serivice Principal, saját ACR?
Az ACR basic is napi 0.176 dollár, ettől megijedtem, ezért gondoltam a Mentorklubban csinálni. De most már lehet hogy azt a 2 napot kibírom az előfizetésemmel, ha a mentorklubost sehogy se tudom használni.
Tehát akkor ezt a connection-t nem tudom használni akkor se ha a Mentorklubban hozok létre pipeline-t?
  dockerRegistryServiceConnection: "f4f94a44-0505-4235-9347-4926b8fef7a4"
  imageRepository: "trn-node-docker"
  containerRegistry: "mentorklub.azurecr.io"

**Comment by Gomboc7** [comment]
Akkor ezt nem értettem, tegnap még mindenáron új organization-t
létrehozni,  ma meg már mutatja a tiédben a Mentorklubot... miután beléptem
az adott linkkel. cool...



Csak erre a linkre jön be a mit küldtél:

Tibor Kiss ***@***.***> ezt írta (időpont: 2024. nov. 24., V,
23:06):

**Comment by the1bit** [comment]
Szia,

Mindig új Organisation-t kér, hogy hozz létre amikor először használod. 
Gondolj bele! Amikor az Azure DevOps-ot elkezded használni, akkor az alkalmazás nem feltételezheti, hogy Te egy megosztott projekthez szeretnél hozzáférni. Tehát segít neked, hogy el tudd kezdeni az első projektedet. Ahhoz pedig egy Organisation-re lesz szükséged.

Nézd dolgokat azok szemével is ilyenkor, akik segítség nélkül kezdenek bele ebbe a világba. Ha így teszel, érthetőek lesznek számodra is ezek a lépések. :-)

Igen, az ACR basic napi 0.176 dollár. Összesen 5 dollár (2 000 Ft) havonta. Az nagyon olcsó. Ha szeretnél a felhőben elmélyedni, akkor az elején szükséged lesz befektetésre. Ez vele jár, azonban 100-szorosan megtérül később. :-)

A gyakorló környezetnek is van költsége, amit mi fizetünk. Szerinted az mennyi? :-)

**Comment by Gomboc7** [comment]
Nekem volt már saját organisation-om, és projektem is korábbi leckék miatt.
Ezért nem értem, hogy miután beléptem a Cloudstake-be, utána a devops-ban
miért akarja, hogy a  új organisationt hozzak létre?

Tibor Kiss ***@***.***> ezt írta (időpont: 2024. nov. 25.,
Hét 10:31):

**Comment by Gomboc7** [comment]
Egyébként én nem ott kaptam ezt az errort amit küldtem, amiről te beszéltél a service connection létrehozásnál, hanem a pipeline létrehozása után, és miután leszedte már a GitHub-ról a kódot és akarta futtatni.

**Comment by Gomboc7** [comment]
Na most létrehoztam egy saját ACR-t az én előfizetésemben:
![image](https://github.com/user-attachments/assets/ad6e8ca3-f1a0-471d-85f6-45f5028e5e6e)

Meg egy service connection-t ehhez a projektemből:
![image](https://github.com/user-attachments/assets/c4a8efc9-d66a-4027-9db4-b8d054c48d58)

És beírtam ezt az ID-t a kódomba.
![image](https://github.com/user-attachments/assets/a71b6d2c-6bdb-4a2a-825a-1cf21c2b0d89)

Majd mikor akartam mergelni egy pull request-el a Gitből, és az Azure check hibára futott:
![image](https://github.com/user-attachments/assets/0d78cbca-c36b-4a5b-9a28-7a1444c17651)

A Details-re kattintva ezt a hibát látom:
![image](https://github.com/user-attachments/assets/95c30952-4415-4d6c-a89b-58d27d062fc3)


There was a resource authorization issue: "The pipeline is not valid. Job Build: Step Docker input containerRegistry references service connection 30fcbe04-1556-4425-a7b8-8ed5516617f6 which could not be found. The service connection does not exist, has been disabled or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

Miért mondja, hogy nem létezik a service connection? Ott van a mellékelt képernyőn. Minden grant jogot megadtam neki az összes pipeline-ra

**Comment by Gomboc7** [comment]
valamiért a Mentorklubban próbálja létrehozni a Pipeline-t pedig lgombos2-ben hoztam létre a proba Azure project-ben.
Nem tudom hol csúszik el a dolog...
![image](https://github.com/user-attachments/assets/dd443afa-2147-4de2-8700-b674d7c6accf)

**Comment by the1bit** [comment]
Nagyon becsülöm benned, hogy próbálkozol. Azonban azt látom, hogy összekevered folyamatosan a projecteket és hogy melyik erőforrás hol található. Ezen felül figyelmen kívül a jogosultságokat.

A MentorKlub Azure DevOps project az én Azure Képzés fiókommal van összekötve. 

Hiába állítod át a pipeline-t, hogy a Te ACR-ed használja (ami egy másik előfizetésben van), és hiába adod meg a Te projektekben lévő service connection azonosítóját, az nem fog működni, mert az a service connection nem létezik a MentorKlub projektben.

Ha a MentorKlub projektben hozod létre a pipleine-t akkor ott kell mindent beállítani és ha a sajátodban, akkor ott.

**Comment by Gomboc7** [comment]
Ja, szenvedek mint malac a jégen....
Valamiért a rendszer folyamatosan visszaugrik a Mentorklubba, nem tudom miért. 
Most végre sikerült rávenni, hogy az én projectembe dolgozzon, a CD-t meg is csinálta, de a CI-t skippelte:

![image](https://github.com/user-attachments/assets/f98ba0b2-5c01-4237-a2ff-2d08522e5cd7)

**Comment by the1bit** [comment]
Ez így rendben van.

Szerintem nézd vissza az idevágó videót, mert abban minden benne van. Az is, hogy a CI-t miért skip-elte. :-)

**Comment by Gomboc7** [comment]
Köszi, most már sikerült.

**Comment by the1bit** [comment]
Szívesen :-)
