### ISSUE TITLE
[I]: észrevétel és hiba - videós becsatlakozás során

### ISSUE THREAD

**Issue by istilino** [cloudsteak/mentor-klub-cloud#14]
### Mi történt?

Kedves Tibor!

Köszönöm az utólagos betekinthetőséget is ebbe a 7 alkalmas képzésbe.
Két dolgot jelzenék:

1. A feltűntetett ajánlott oktatóanyagok és képzések:
A Microsoft Azure Cloud alapozó képzés - (prémium élő egynapos tréning)
sajnos nem visszanézhető már, lejárt, az ilyen képzések előtt nem tudom van-e lehetőség hosszabb időre kint hagyni.

2. A másik az Azure bejelentkezés. A .pdf segédlet alapján már a 18. ponttól nem a leirás szerint viselkedik nekem a rendszer, ha a saját email cimmel (ugyirat@gmail.com) jelentkezek be, 
akkor mintha egy teljesen más tenantba kerülnék. 
Bérlő azonosítója
c2bfa230-f48f-40ea-a2a7-d116489de4be

Küldtem ma új kérést a hozzáféréshez.

Üdvözlettel,
Szépvölgyi István

### Témakör

Azure

**Comment by the1bit** [comment]
Szia @istilino 

1. Erre nekem sajnos nincs ráhatásom, a Mentor Klubbot keresd ezzel. :-)

2. Nekem most is úgy viselkedik ahogy kell. Tudnál esetleg képernyőképet vagy valami bővebb információt adni a jelenség kapcsán?

Köszönöm


Üdv:
Tibi

**Comment by istilino** [comment]
15.pont
![image](https://github.com/user-attachments/assets/c476775c-6bef-4a9d-9701-c9e8f52f7ff1)

16-17 pontnál nem már az authenticator alkalmazásra nem is volt gombom
18. pont
![image](https://github.com/user-attachments/assets/9779cca2-21de-446a-ac23-061defdf5399)

A képeket látod igy beillesztve vagy átküldjem emailben?

(bocsánat, hosszú i betű nincs a laptop billentyűzetemen...)

![15_pont](https://github.com/user-attachments/assets/3fc3c644-1b14-4acb-a8af-79e250110ae3)
![18_pont](https://github.com/user-attachments/assets/5c74a277-f24a-4286-9139-1bb0e08ebdaf)

Üdv,
István

**Comment by the1bit** [comment]
Szia,

Valamit nem jól csinálsz. Az egyik lépésnél nem. megfelelő lehetőséget választod, vagy már be vagy jelentkezve egy másik felhasználóval. Javaslom, hogy próbáld meg `Incognito window`-ban végigcsinálni a regisztrációt.

Tegnap végigteszteltem a bejelentésed után egy véletlenszerű email címmel a folyamatot és minden lépés tökéletesen egyezett a dokumentumban leírtakkal.

Töröljem felhasználódat és megpróbálod újra?

Köszi

**Comment by istilino** [comment]
Szia,
Igen, légy oly kedves és töröld,
szükség esetén küldök új igényt erről..

Üdv,
István

**Comment by istilino** [comment]
Szia Tibi!

Valami ősrégi dolgomat benéznem, hogy a jobb felső sarokban a usernél kellett a cimtár cserét nyomni, viszont gy még a 2FA beálltiást  nézegetnem kell: 


Üdv,
István

**Comment by the1bit** [comment]
Szia,

Nagyon örülök, hogy sikerült. 🙂

T.
