### ISSUE TITLE
[I]: AI demo hiba - Webalkalmazás létrehozása Chatbothoz Azure-ban

### ISSUE THREAD

**Issue by istilino** [cloudsteak/mentor-klub-cloud#15]
### Mi történt?

Kedves Tibor!

(Velem vagy nálam mindig gond van :) )
Szeretett Azure-os haladó videóid utolsó AI témakörben tesztelnék. A dec.9-es elérhetőség miatt kipróbáltam a webalkalmazás létrehozást, amely az alábbi hibát adja. Az erőforrás újrainditása és órák eltelte sem oldja meg:
https://ai-techq4a-20241205.azurewebsites.net/
![image](https://github.com/user-attachments/assets/8e56d7ea-ca2b-4510-b244-0f902355a5e5)

Van ötleted esetleg?
Hova nem  tud authentikálni a userem (ugyirat@gmail.com)?

u.i. Git-es és AWS clous kérdéseket hova lehet küldeni?

Köszönettel és üdvözlettel,
István

### Témakör

Azure

**Comment by the1bit** [comment]
Szia,

Próbáltad újraindítani azóta a webapp-ot? Esetleg letörölni, majd újra létrehozni?

**Comment by istilino** [comment]
Szia!

Minden tanácsodat megfogadva (újraindÍtás, törlés, majd létrehozás más névvel) után is sajnos ugyanez a helyzet, több böngészőben is próbáltam. :(
Mivel a videón jól működik, úgy is nagyon tetszik és a lényege átjön.
Valós helyzetben, mint a példa is mutatja, üzemeltetésileg nem tudnám megoldani :)

Üdv,
István

**Comment by the1bit** [comment]
Szia,

Sikerült reprodukálnom nekem is a hibát. 
Kiderült, hogy nincs beállítva felhasználói hitelesítés. Miután manuálisan beállítottam nálam, a hiba továbbra is fennáll. :-(
 
Most nyitottam egy estet a Microsoft-nál, mert nem működik a a felhasználói azonosítás a hivatalos dokumentáció alapján sem.

Szerertnék elnézést kérni Tőled, hogy belefutottál egy Azure hibába és emiatt nem tudod most tesztelni ezt a funkciót.

Konklúzió: Meg tudnd oldani valós helyzetben is, ha az Azure úgy működne, ahogy kellene. :-)

Üdv:
Tibi

**Comment by istilino** [comment]
Kedves Tibor!

Köszönöm a visszajelzést, emiatt ne maradjon nyitva ez az issue sem :)

Üdvözlettel,
István

**Comment by the1bit** [comment]
Én köszönöm. :-)

Amint lesz olyan megoldás, ami szükséges a működéshez azonnal frissítem a dokumentációt is.
