### ISSUE TITLE
[Q]: Docker Registry

### ISSUE THREAD

**Issue by Gomboc7** [cloudsteak/mentor-klub-cloud#16]
### Miben segíthetek?

Szia Tibor,
Beszéltünk róla, hogy az Azure Container registry szolgáltatása pénzbe kerül. 
De használhatjuk a Docker Hub-ot is erre a célra nem? Össze lehet kötni az Azure-ral, ugye? 
Meg a Github-nak is van valami Docker registryje, csak nem értem, hogy az mintha organization-oknak lenne csak, privátban nem, vagy tévedek?

Köszi!
Laci

### Témakör

Docker

**Comment by the1bit** [comment]
Szia,

Igen, használhatod a DockerHub-ot is, de az sem ingyenes egy bizonyos kérésszám után. 

A Docker Hub-ot is összetudod kötni az Azure Webapp-al

**Comment by the1bit** [comment]
A GitHub-nak is van valóban image registry-je. 
Azt azonban egyelőre nem lehet Azure-al még összekötni.

**Comment by Gomboc7** [comment]
Köszi

**Comment by the1bit** [comment]
Szívesen, bármikor. :-)
