### ISSUE TITLE
[Q]: AWS költségek csökkentése

### ISSUE THREAD

**Issue by istilino** [cloudsteak/mentor-klub-cloud#17]
### Miben segíthetek?

Kedves Tibor!

Az AWS videód alapján készÍtem magamnak a VPC Peering demó környezetet ( a VPC1 után), ám közben azt láttam a költségkeretek között, hogy önmagában pár nap alatt az Amazon Virtual Private Cloud "rohamos" mértékben viszi az aprópénzt. 
![image](https://github.com/user-attachments/assets/8380b6c2-8c08-409e-9ef5-c622d55833ea)

Hogyan lehet a VPC-t, akár mint erőforrást kvázi leállÍtani? Hogyan lehet költséghatékony egy tanulási célú demő rendszer?
Ha a demó végén törölnék mindent (a már bele regisztrált domain névvel), azt hogyan tehetem meg?
Minden egyes albeállÍtást(erőforrást) kell törölni és utána a fő erőforrásokat vagy komplett van egy gombnyomásos megszüntetési lehetőség?
Ez már majdnem az a kérdés, hogyan költözhetsz ki véglegesen a felhőből?
:)

Üdv,
István

### Témakör

AWS

**Comment by the1bit** [comment]
Szia,

A VPC, az a virtuális hálózat és nem kerül semmibe, azaz INGYENES. :-)

Amit látsz a képen az a Peering és a VPN ára lehet, ami a VPC oldalon jelenik meg.

Amit tenni tudsz:
- VPN törlése (az a legdrágább)
- Peering törlése (ha már nincs rá szükséged)

Egyéb kérdéseidre a válasz:
1. Hogyan lehet költséghatékony egy tanulási célú demő rendszer? - Havi 10 000 Ft-ból egy jó környezetet lehet építeni.
2. Ha a demó végén törölnék mindent (a már bele regisztrált domain névvel), azt hogyan tehetem meg? - Úgy érted, hogy Route 53-ban regisztrált domain név? Azt kifizeted egy évre ha ott regiszrálsz. Azt onnan nem tudod törölni. Egyébként erőforrásokat úgy tudsz törölni, hogy mindent kitörölsz. És a végén a fiókot (is ki tudod törölni)
3. Minden egyes albeállÍtást(erőforrást) kell törölni és utána a fő erőforrásokat vagy komplett van egy gombnyomásos megszüntetési lehetőség? - A **Close Account** lehetőség esetén töröl minden erőforrást.

Remélem ez segít.

Üdv:
Tibi

**Comment by istilino** [comment]
Szia!

Köszönöm az iránymutatásokat, továbbra is nő a költség apránként, úgyhogy egyelőre csak a VPN-t tudtam törölni, mert a demóból a VPC2-t és a Peeringet még nem teszteltem, de ki fogom próbálni, hogy átlássam a teljesebb költségszerkezetet.
Sok beépÍtett semmitmondó riport és egyéb keresés után találtam meg azt az aloldalt, ami már jól részletezi a költségeket:
https://us-east-1.console.aws.amazon.com/billing/home#/bills 
Ezekből a mai napi adatokat elteszem, és keresni fogom a különbségeket:

![image](https://github.com/user-attachments/assets/9b180188-9212-4713-9059-be44c7951005)

![image](https://github.com/user-attachments/assets/4489475c-8044-4cd9-8cd5-1c69517554dd)

![image](https://github.com/user-attachments/assets/44d8f252-8892-46fc-82ed-a5348ef3bf66)

TAX értelemszerű :)
![image](https://github.com/user-attachments/assets/374171b2-561b-4b48-bcf1-18e4bf1d4c15)

Mindent köszönök, szerintem zárható az issue,
igyekszem a tanácsaid alapján hosszabb távon kordában tartani, amit lehet :)

Üdv,
István

**Comment by the1bit** [comment]
Szia,

Azért itt több olyan erőforrás is van ami láthatóan növeli a költségeket. 

- NAT Gateway
- EIP (nyílvános IP)

NAT gateway gyakorló környezetre felesleges, mert nem szoktuk ilyen szigorúan elszeparálni a subnet-eket. Ha nyílvános subnetekkel dolgozol gyakorlásként és csak indokolt esetben használsz NAT gateway-t a private subnetekben lévő EC2 instance-okhoz, akkor máris sokat spórolsz.

És igen, a VPN ott van a legmagasabb költséggel.


Menni fog ez. Lehet nem azonnal, de rá fogsz érezni. Igyekezz tudatosan építkezni és rendszeresen analitzálni a költségeket. :-)

Örülök, ha segítettem.

Üdv:
Tibi
