### ISSUE TITLE
kapcsolatfelvetel

### ISSUE THREAD

**Issue by ffrriiccii** [cloudsteak/mentor-klub-cloud#2]
Kedves Tibor!
Csütörtökön este a "különórán" Vilmos kért tőlem valamit, de nem tudtuk megbeszélni mert amint kiléptél vége lett a zoom chat-nek is. :-)
Nekem nincs elérhetőségem hozzá, neki sincs hozzám. Ha szépen megkérlek, megtennéd hogy át küldöd neki a nagyon kezdetleges linkedin profilomat, hogy tudjon nekem üzenni?

https://www.linkedin.com/in/laszlo--nemeth/

Köszönöm szépen:
Plusz köszönöm a 2. jóváhagyást, most nem csúsztam ki a 24h-ból :-)

Frici

**Comment by the1bit** [comment]
Bocsánat. :-)
