### ISSUE TITLE
Azure email

### ISSUE THREAD

**Issue by kuvaszdzsi** [cloudsteak/mentor-klub-cloud#3]
### Miben segíthetek?

[Q]: Nemrég kaptam váéaszt a lecsooo@gmail.com email címre Azure belépéssel kapcsolatosan.  Viszont megint nem kaptam semmi emailt, megnéztem a spam-ek között is! 

### Témakör

Általános kérdés

**Comment by the1bit** [comment]
Szia @kuvaszdzsi ,

Nézz még körbe magadnál, mert veled párhuzamosan még 4-5 ember igényelt ugyanilyen hozzáférést és mindegyikük azóta használja is azt.

Kiküldöm újra. :-)
