### ISSUE TITLE
Azure hozzáférés

### ISSUE THREAD

**Issue by gaborsandor132** [cloudsteak/mentor-klub-cloud#4]
### Mi történt?

Kedves Tibor!

Vasárnap vissza szerettem volna nézni a csütörtöki Docker alapú alkalmazások Cloud-ban előadást és igényeltem azure hozzáférést és nem kaptam e-mailt, nem jött meg ezzel kapcsolatban a levél az e-mail címemre. Tudnál ebben segíteni?

Köszönettel,
Sándor Gábor
E-mail: gaborsandor132@gmail.com

### Témakör

Azure

**Comment by the1bit** [comment]
Kedves Gábor,

köszönöm, hogy írt.

Láttam az igényeket. Jóvá is hagytam mindet.
A levélszemét mappát megnézte? Sajnos előfordul, hogy ott landolnak az email-ek.

várom visszajelzését.

Üdv:
Tibi

**Comment by gaborsandor132** [comment]
Néztem a spamet, de ott sem volt, rá is frissítettem. Vasárnap is küldtem igényt meg most is nem is olyan régen, de sajnos semmi.

**Comment by the1bit** [comment]
Megnéztem a teljes folyamatot és az egyik secret járt le, azért nem ment végig a folyamat.

Most javítottam, így már meg is kellett hogy érkezzen a jóváhagyás.

Kérem, igazolja vissza. 

Köszönöm 🙂

**Comment by gaborsandor132** [comment]
Most már megjött az e-mail.
Köszönöm a segítséget :)

**Comment by gaborsandor132** [comment]
Elfogadtam a meghívót, kaptam egy kódot, amit be is illesztettem. Tovább irányított az oldalra, ahol be lehet jelentkezni az azure-be, beírom az e-mail címemet és azt a hibaüzenetet írja ki, hogy nem található fiók a megadott felhasználónévvel.

**Comment by the1bit** [comment]
Szia,

Az email-ben található videó utasításaid ha követi, akkor biztosan sikerülni fog. A felhasználó rendelkezik a megfelelő jogosultságokkal. Ezt ellenőriztem is. 🙂

**Comment by gaborsandor132** [comment]
Szia,

Közben rájöttem és elkezdtem beállítani, csak még nem akartam írni, amíg nem sikerült megcsinálnom, hálás köszönet érte :)

**Comment by the1bit** [comment]
Nagyon örülök. 🙂

Köszi a visszajelzést. 🙂
