### ISSUE TITLE
[I]: Loadbalancer demo videót

### ISSUE THREAD

**Issue by lxMagicxl** [cloudsteak/mentor-klub-cloud#5]
### Mi történt?

Hello 
 A load ballancer demo videóban 5:59kor amikor kiválasztod a publikus subnetet utána nem engedi tovább vinni (létrehozni) a loadbalancert mert hogy kér még egy subnetet most vc1ben csak egy db publikus subnet van a másik private mi a teendő? 
![image](https://github.com/cloudsteak/mentor-klub-cloud/assets/173693255/f2d64d02-641b-440e-b897-9f94a8c2e746)
![image](https://github.com/cloudsteak/mentor-klub-cloud/assets/173693255/367cc0f5-7c6c-4ca5-96f6-746dc039a93c)

Köszi Dani

### Témakör

AWS

**Comment by the1bit** [comment]
Szia,

Köszi, hogy írtál.

Valóban kér egy másik subnet-et is. **Nyugodtan válaszd ki a privát subbet-et is (ugyanabban a VPC-ben)
Ez esetben tovább enged és a működést nem befolyásolja.**

Ez a viselkedés a videó elkészülte után jelent meg, hogy még jobban ösztönözze a felhasználókat a magas-rendelkezésreállású rendszerek kiépítésére.

Kérlek, jelezz vissza a megoldás kapcsán.

Köszi.

**Comment by the1bit** [comment]
Itt a teljes megoldás: https://github.com/cloudsteak/trn-aws-common/blob/main/ec2.md#terheléselosztó-load-balancer
