### ISSUE TITLE
[Q]: A többhtes Azure képzésre utalásokkal kapcsolatos kérdés

### ISSUE THREAD

**Issue by tanker11** [cloudsteak/mentor-klub-cloud#6]
### Miben segíthetek?

Szervusz Tibor!

Az Azure haladó képzésen említed többször is, hogy a többhetes képzés kapocsán lehet hozzáférést kapni teszteléshez az Azure-ban. Legalábbis ha jól értettem. Ez igaz?
Illetve ha igen, akkor ez már volt/van/lesz? Ugyanis nem látom a Gerilla Mentorklub alatt...

Előre is köszönöm:
Tanka Róbert

Ui: szuper részletesek a képzéseid!

### Témakör

Általános kérdés

**Comment by the1bit** [comment]
Szia Róbert (@tanker11 ),

Igen, ez igaz és most is van lehetőséged erre.
A több hetes Azure képzés oldalán a Mentor Klubban (https://gerillamentorklub.hu) megtalálsz minden információt ehhez. Ha valamiért mégsem akadsz rá, írj nyugodtan az ügyfélszolgálatnak és segítenek eligazodni. 
Mások is így igényelnek hozzáférést. 😊


Remélem hamarosan találkozunk egy oktatáson. ☺️

És nagyon köszönöm az elismerő szavakat.

Üdv:
Tibi

**Comment by tanker11** [comment]
Szia Tibi!

Köszönöm, megtaláltam a közelgő (október 14-én induló) képzések között, és
igényeltem is hozzáférést! :)
Ez nagyon hasonlónak tűnik a folyamatosan elérhető rögzített videós tréning
tematikájához. Ez nagyjából ugyanaz lesz?

Mindenképp jövök azért, ha nem is mindig élőben - nagyon szimpatikus
ugyanis a "dolgozzunk össze!" hozzáállásod, még ha most állást is keresek
épp. Sok IT alapom van, de egy ideig nem használtam. Elevenítem őket a
tréningeken, megfűszerezem projektmenedzsmenttel és vastag felhős
gyakorlással. Remélem, meglesz az eredménye - többet ülök gép előtt, mint
amikor dolgoztam! :D
Van egy jóbaráton keresztüli külföldi DevOps ismerősöm, ha eleget tudok
már, akkor majd merek tőle kérdezni., hátha be lehet dolgozni pár órában,
hogy gyakorlatot szerezhessek.
Tényleg, Te nem tudod, Magyarországon is elérhető ilyen "side project"
jellegű munka?

Üdv:
Tanka Robi

Tibor Kiss ***@***.***> ezt írta (időpont: 2024. szept. 3.,
K, 23:47):

**Comment by the1bit** [comment]
Szia,

Igen, láttam az igényed. Gyorsan jóvá is hagytam. :-)

A tematika lehet hasonló, de a több hetes képzés egy teljesen más jellegű tudásra öszpontosít. És az Azure Haladó képzls jóval több mindent lefed és azokat is részletesen. A többjetesen viszont ki vannak emelve azon fontosabb témák, amelyeket jobb élőben bemutatni. :-)

Örülök, hogy tanulsz. Én is igyekszem sokat a mai napig. Most éppen az új blogomat csinosítom, ami szintén nektek szól majd. https://cloudmentor.hu

Side project-ek mindig hasznosak. Azonban nincs rálátásom az itthoni helyzetre.

Hamarosan találkozunk. 

Jó tanulást.

Üdv:
Tibi

**Comment by tanker11** [comment]
Köszönöm szépen a jóváhagyást!
Van vele egy kis gondom, sajnos.
A háttértörténet, hogy egy teljesen más okból pár hónapja létrehoztam egy
Azure accountot a ***@***.*** userrel.
Ebben szépen leketyegett a 200USD-s keret, így a nemrég elkezdett képzéshez
kénytelen voltam kiszenvedni egyet a feleségem emailjére (és
bankkártyájára... ;) )
Utóbbi talán nem is annyira fontos, de most, amikor elfogadtam volna a
meghívást, akkor be akart jelentkezni a portálra a ***@***.***
userrel, de jelszót kért, és amit a böngésző automatikusan beleírt, azt nem
fogadta el.
Most így nem tudom, milyen státuszba kerültem...

Ne fáradj vele ma, de ha tudsz benne segíteni, megköszönném, ha helyre
tudnánk hozni valamikor.

Előre is köszönöm:
Robi


Tibor Kiss ***@***.***> ezt írta (időpont: 2024. szept. 4.,
Sze, 20:00):

**Comment by the1bit** [comment]
Kitöröltelek. Kezd elölről. Igénylés... :-)

**Comment by tanker11** [comment]
OK, igényeltem.
Félek, ugyanabba futunk bele, de meglátjuk... :)

Tibor Kiss ***@***.***> ezt írta (időpont: 2024. szept. 4.,
Sze, 20:23):

**Comment by tanker11** [comment]
Köszönöm, azt hiszem, bejutottam:
[image: image.png]

egyedül a több faktoros hitelesítést nem sikerült még kicsikarnom. Az a
felületről is tudom majd kezdeményezni?
Most egyszer használatos kódot kértem az emailemre.

Üdv:Robi

Tibor Kiss ***@***.***> ezt írta (időpont: 2024. szept. 4.,
Sze, 20:25):

**Comment by the1bit** [comment]
Egyszer használatos kód is jó. :-)

**Comment by tanker11** [comment]
Rendben, akkor nem zavarlak tovább, és várom a képzést!
Mégegyszer nagyon köszönöm!

Tibor Kiss ***@***.***> ezt írta (időpont: 2024. szept. 5.,
Cs, 13:09):

**Comment by tanker11** [comment]
Kedves Tibor!

Valamiért nem látszik a fiókomban többé a CloudSteak directory.
FYI, a Microsoft Learn oldalán tanulok sokat, és a gyakorlatokhoz szokott
sandboxot hozzárendelni a fiókhoz. Ennek lehet köze a fentihez?

Ha nem nagy gond, szeretnék továbbra is gyakorolni a rendszeren.

Köszönettel:
Tanka Róbert


Róbert Tanka ***@***.***> ezt írta (időpont: 2024. szept. 5.,
Cs, 16:39):

**Comment by the1bit** [comment]
Szia,

Mindenképpen fontos, hogy nézd meg hogy melyik felhasználó aktív éppen a Portálon. Mivel az Azure esetén egyszerre több felhasználóval lehetsz bejelentkezve, amelyeknek akár ugyanahhoz az előfizetéshez is lehet joga, így könnyen összezavarodhat az ember.

Ellenőrizd a jobb felső sarokban, hogy melyik felhasználóval vagy bejelentkezve, mert előfordulhat, hogy a sandbox bejelentkezések miatt nem látod a CloudSteak directory-t.

**Comment by tanker11** [comment]
Szia Tibor!

Sajnos élőben nem tudok ott lenni a tréningeken, de mindig megnézem utólag!
Amióta beszéltünk, letettem az AZ-900 vizsgát - komolyan gondolom! :)
Ezen felül DP learning anyagokat nézek át nagy sebességgel, és data
pipeline-ek építését gyakorolom, mert ilyen állásokra jelentkezem.
A több hetes gyakorlásnak van is eredménye mára. Szerencsére Pythonból és
SQL-ből már felhoztam magam a nyáron, úgyhogy kezd kialakulni egy ütős kis
tudáskészlet.

Persze nagyon sok tanulás van még előttem, de más nem csak szenvedés, hanem
élvezet is.

Újra kértem engedélyt a mentor előfizetéshez, mert a régebbi már nem igazán
működött.

Üdv, és köszönöm a tudás megosztását!

Szuperül fejlődik a weboldal is!

Tanka Robi


Tibor Kiss ***@***.***> ezt írta (időpont: 2024. szept. 27.,
P, 7:57):
