### ISSUE TITLE
[Q]: Azure 7 hetes képzés, új ígénylés

### ISSUE THREAD

**Issue by nviliam** [cloudsteak/mentor-klub-cloud#7]
### Miben segíthetek?

Szia Tibor!

Az Azure 7 hetes képzés Azure hozzáférés kérelmemnél automatikusan a gmail-es email címemet gépeltem be (azt használom gyakrabban), de közben rájöttem, hogy korábban már regisztráltam egy másik email címemmel (és bankkártyával) az Azure-re. Ha nem gond, küldenék egy másik igénylést a már regisztrált emaillel (yahoo), hogy ne legyen ütközés. A gmail-est nyugodtan töröld, ha szükséges.

Segítségedet előre is köszönöm!

Üdv,
Nagy Viliam

UI: Nagyon jó a képzés! Alig várom, hogy gyakorolhassak! :)

### Témakör

Azure

**Comment by the1bit** [comment]
Szia,

Megkaptam mindkét igényt és jóvá is lett hagyva. :-)

Köszönöm, hogy jelezted. :-)
