### ISSUE TITLE
[I]: mentorklub erőforrás csoport használata nem választható

### ISSUE THREAD

**Issue by BeniBenB** [cloudsteak/mentor-klub-cloud#8]
### Mi történt?

Szia Tibor!

Valamilyen oknál fogva nem tudok virtuális gépet létrehozni, nem választható nálam a mentorklub erőforrás csoport. Előadáson azt mondtad hogy ebben dolgozzunk de valahogy nem érem el.

Mit ronthatok el?
![Vágólap_10-17-2024_01](https://github.com/user-attachments/assets/a370269c-1822-4fb5-ae5f-a401dc7e42a5)

ui.: Gondolo a fenti okok miat a Svéd régió sem választható nálam.

### Témakör

Azure

**Comment by the1bit** [comment]
Szia,

Az erőforráscsoport választása fölött látod, hogy nem a megfelelő előfizetés van kiválasztva.

Ott ki kell választanod az “Azure Képzés” előfizetést.

Lehet nem jó címtárba (bérlő, tenant) vagy bejelentkezve.

🙂

**Comment by BeniBenB** [comment]
Köszönöm címtár gond volt, most jó.

**Comment by the1bit** [comment]
Szívesen
